name: apple-photos-aura-frame-syncer
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi==0.116.1
      - uvicorn==0.35.0
      - osxphotos==0.72.1
      - selenium==4.34.2
      - jinja2==3.1.6
      - python-multipart==0.0.20
      - aiofiles==24.1.0
      - httpx==0.28.1
      - pydantic==2.11.7
      - requests==2.32.4
      - python-dotenv==1.1.1
      - PyGithub==2.6.1
      - schedule==1.2.1